server:
  port: 3200
spring:
  datasource:
    hikari:
      connection-test-query: SELECT 1
      allow-pool-suspension: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  config: classpath:logback-${spring.profiles.active}.xml
---
spring:
  profiles: dev
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/todo?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: lightene
      password: lyder11475
---
spring:
  profiles: production
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/todo?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: lightene
      password: lyder11475

